-- Amorce la table de reconnaissance avec des produits courants (alimentaire + entretien/hygiène)
-- et leurs abréviations habituelles sur les tickets de caisse français.
-- S'applique au foyer déjà créé (il n'y en a qu'un dans cette appli).

insert into product_aliases (household_id, raw_text, canonical_name)
select h.id, v.raw_text, v.canonical_name
from households h
cross join (values
  -- Produits laitiers / œufs
  ('lait demi ecreme', 'Lait demi-écrémé'),
  ('lait 1 2 ecr', 'Lait demi-écrémé'),
  ('lait entier', 'Lait entier'),
  ('lait ecreme', 'Lait écrémé'),
  ('yaourt nature', 'Yaourt nature'),
  ('yaou nat', 'Yaourt nature'),
  ('yaourt fruits', 'Yaourt aux fruits'),
  ('yaourt grec', 'Yaourt grec'),
  ('fromage blanc', 'Fromage blanc'),
  ('beurre doux', 'Beurre doux'),
  ('beurre demi sel', 'Beurre demi-sel'),
  ('fromage rape', 'Fromage râpé'),
  ('creme fraiche', 'Crème fraîche'),
  ('camembert', 'Camembert'),
  ('emmental', 'Emmental'),
  ('mozzarella', 'Mozzarella'),
  ('oeufs x6', 'Œufs (x6)'),
  ('oeufs x12', 'Œufs (x12)'),
  ('oeufs', 'Œufs'),
  -- Boulangerie
  ('pain de mie', 'Pain de mie'),
  ('baguette', 'Baguette'),
  ('baguette tradition', 'Baguette tradition'),
  ('brioche', 'Brioche'),
  ('croissants', 'Croissants'),
  ('pain complet', 'Pain complet'),
  -- Fruits et légumes
  ('pommes', 'Pommes'),
  ('bananes', 'Bananes'),
  ('oranges', 'Oranges'),
  ('citrons', 'Citrons'),
  ('tomates', 'Tomates'),
  ('salade', 'Salade'),
  ('laitue', 'Salade'),
  ('oignons', 'Oignons'),
  ('ail', 'Ail'),
  ('carottes', 'Carottes'),
  ('pommes de terre', 'Pommes de terre'),
  ('pdt', 'Pommes de terre'),
  ('pdt bio', 'Pommes de terre'),
  ('courgettes', 'Courgettes'),
  ('poivrons', 'Poivrons'),
  ('champignons', 'Champignons'),
  ('concombre', 'Concombre'),
  ('avocat', 'Avocat'),
  ('poireaux', 'Poireaux'),
  ('brocolis', 'Brocolis'),
  ('epinards', 'Épinards'),
  ('fraises', 'Fraises'),
  ('raisins', 'Raisins'),
  ('kiwis', 'Kiwis'),
  ('poires', 'Poires'),
  -- Viande / poisson
  ('poulet', 'Poulet'),
  ('blanc de poulet', 'Blanc de poulet'),
  ('escalope poulet', 'Escalope de poulet'),
  ('steak hache', 'Steak haché'),
  ('viande hachee', 'Viande hachée'),
  ('jambon blanc', 'Jambon blanc'),
  ('jb blc', 'Jambon blanc'),
  ('lardons', 'Lardons'),
  ('saucisses', 'Saucisses'),
  ('saumon', 'Saumon'),
  ('thon', 'Thon'),
  ('crevettes', 'Crevettes'),
  -- Épicerie sucrée / salée
  ('pates', 'Pâtes'),
  ('past sec', 'Pâtes'),
  ('riz', 'Riz'),
  ('farine', 'Farine'),
  ('sucre', 'Sucre'),
  ('sel', 'Sel'),
  ('poivre', 'Poivre'),
  ('huile olive', 'Huile d''olive'),
  ('huile tournesol', 'Huile de tournesol'),
  ('cafe moulu', 'Café moulu'),
  ('cafe dosettes', 'Café en dosettes'),
  ('cafe grains', 'Café en grains'),
  ('the', 'Thé'),
  ('chocolat noir', 'Chocolat noir'),
  ('chocolat lait', 'Chocolat au lait'),
  ('cereales', 'Céréales'),
  ('confiture', 'Confiture'),
  ('miel', 'Miel'),
  ('pain de mie complet', 'Pain de mie complet'),
  ('biscottes', 'Biscottes'),
  ('lentilles', 'Lentilles'),
  ('pois chiches', 'Pois chiches'),
  ('haricots verts', 'Haricots verts'),
  ('mais', 'Maïs'),
  ('olives', 'Olives'),
  ('ketchup', 'Ketchup'),
  ('mayonnaise', 'Mayonnaise'),
  ('moutarde', 'Moutarde'),
  ('vinaigre', 'Vinaigre'),
  ('sauce tomate', 'Sauce tomate'),
  ('soupe', 'Soupe'),
  ('bouillon cube', 'Bouillon cube'),
  -- Boissons
  ('eau minerale', 'Eau minérale'),
  ('eau petillante', 'Eau pétillante'),
  ('jus orange', 'Jus d''orange'),
  ('jus pomme', 'Jus de pomme'),
  ('soda cola', 'Soda cola'),
  ('limonade', 'Limonade'),
  ('vin rouge', 'Vin rouge'),
  ('vin blanc', 'Vin blanc'),
  ('biere', 'Bière'),
  -- Surgelés / snacks
  ('legumes surgeles', 'Légumes surgelés'),
  ('pizza surgelee', 'Pizza surgelée'),
  ('frites surgelees', 'Frites surgelées'),
  ('glace', 'Glace'),
  ('chips', 'Chips'),
  ('biscuits', 'Biscuits'),
  ('bonbons', 'Bonbons'),
  ('barres cereales', 'Barres de céréales'),
  ('fruits secs', 'Fruits secs'),
  -- Hygiène
  ('dentifrice', 'Dentifrice'),
  ('shampoing', 'Shampoing'),
  ('gel douche', 'Gel douche'),
  ('papier toilette', 'Papier toilette'),
  ('pq', 'Papier toilette'),
  ('savon', 'Savon'),
  ('deodorant', 'Déodorant'),
  ('brosse a dents', 'Brosse à dents'),
  ('coton tiges', 'Coton-tiges'),
  ('rasoirs', 'Rasoirs'),
  ('mouchoirs', 'Mouchoirs'),
  ('proteges slips', 'Protège-slips'),
  ('serviettes hygieniques', 'Serviettes hygiéniques'),
  ('creme hydratante', 'Crème hydratante'),
  -- Entretien maison
  ('lessive', 'Lessive'),
  ('liquide vaisselle', 'Liquide vaisselle'),
  ('eponges', 'Éponges'),
  ('sacs poubelle', 'Sacs poubelle'),
  ('essuie tout', 'Essuie-tout'),
  ('nettoyant menager', 'Nettoyant ménager'),
  ('javel', 'Eau de Javel'),
  ('assouplissant', 'Assouplissant'),
  ('sac congelation', 'Sacs de congélation'),
  ('film alimentaire', 'Film alimentaire'),
  ('papier aluminium', 'Papier aluminium'),
  ('ampoules', 'Ampoules'),
  ('piles', 'Piles'),
  ('allumettes', 'Allumettes'),
  ('bougies', 'Bougies')
) as v(raw_text, canonical_name)
on conflict (household_id, raw_text) do nothing;
